const GET_DATA = "GET_DATA";
const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
const GET_DATA_FAILED = "GET_DATA_FAILED";

const POST_NUMBER = "POST_NUMBER";
const ADD_INGREDIENT = "ADD_INGREDIENT";
const PUT_AWAY_INGREDIENT = "PUT_AWAY_INGREDIENT";
