export const FETCH_INGREDIENTS: 'FETCH_INGREDIENTS' = "FETCH_INGREDIENTS";
export const FETCH_INGREDIENTS_STATE: 'FETCH_INGREDIENTS_STATE' = "FETCH_INGREDIENTS_STATE";
export const FETCH_INGREDIENTS_ERROR: 'FETCH_INGREDIENTS_ERROR' = "FETCH_INGREDIENTS_ERROR";
export const FETCH_INGREDIENTS_REQUEST: 'FETCH_INGREDIENTS_REQUEST' = "FETCH_INGREDIENTS_REQUEST";

export const GET_CONSTRUCTOR: 'GET_CONSTRUCTOR' = "GET_CONSTRUCTOR";

export const ADD_INGREDIENT_DETAILS: 'ADD_INGREDIENT_DETAILS' = "ADD_INGREDIENT_DETAILS";
export const DELETE_INGREDIENT_DETAILS: 'DELETE_INGREDIENT_DETAILS' = "DELETE_INGREDIENT_DETAILS";

export const FETCH_INGREDIENTS_ID: 'FETCH_INGREDIENTS_ID' = "FETCH_INGREDIENTS_ID";

export const ORDER_NUMBER: 'ORDER_NUMBER' = "ORDER_NUMBER";
export const ORDER_NUMBER_SUCCESS: 'ORDER_NUMBER_SUCCESS' = "ORDER_NUMBER_SUCCESS";
export const ORDER_NUMBER_ERROR: 'ORDER_NUMBER_ERROR' = "ORDER_NUMBER_ERROR";

export const LOGIN_REQUEST: 'LOGIN_REQUEST' = "LOGIN_REQUEST";
export const LOGIN_SUCCESS: 'LOGIN_SUCCESS' = "LOGIN_SUCCESS";
export const LOGIN_ERROR: 'LOGIN_ERROR' = "LOGIN_ERROR";

export const LOGOUT: 'LOGOUT' = "LOGOUT";
export const LOGOUT_SUCCESS: 'LOGOUT_SUCCESS' = "LOGOUT_SUCCESS";
export const LOGOUT_ERROR: 'LOGOUT_ERROR' = "LOGOUT_ERROR";

export const REGISTER_REQUEST: 'REGISTER_REQUEST' = "REGISTER_REQUEST";
export const REGISTER_SUCCESS: 'REGISTER_SUCCESS' = "REGISTER_SUCCESS";
export const REGISTER_ERROR: 'REGISTER_ERROR' = "REGISTER_ERROR";

export const USER_REQUEST: 'USER_REQUEST' = "USER_REQUEST";
export const USER_SUCCESS: 'USER_SUCCESS' = "USER_SUCCESS";
export const USER_ERROR: 'USER_ERROR' = "USER_ERROR";

export const UPDATE_TOKEN: 'UPDATE_TOKEN' = "UPDATE_TOKEN";
export const UPDATE_TOKEN_SUCCESS: 'UPDATE_TOKEN_SUCCESS' = "UPDATE_TOKEN_SUCCESS";
export const UPDATE_TOKEN_ERROR: 'UPDATE_TOKEN_ERROR' = "UPDATE_TOKEN_ERROR";

export const WS_CONNECTION_START: 'WS_CONNECTION_START' = 'WS_CONNECTION_START';
export const WS_CONNECTION_SUCCESS: 'WS_CONNECTION_SUCCESS' = 'WS_CONNECTION_SUCCESS';
export const WS_GET_MESSAGE: 'WS_GET_MESSAGE' = 'WS_GET_MESSAGE';
export const WS_SEND_MESSAGE: 'WS_SEND_MESSAGE' = 'WS_SEND_MESSAGE';
export const WS_SEND_PONG: 'WS_SEND_PONG' = 'WS_SEND_PONG';
export const WS_CONNECTION_ERROR: 'WS_CONNECTION_ERROR' = 'WS_CONNECTION_ERROR';
export const WS_CONNECTION_CLOSED: 'WS_CONNECTION_CLOSED' = 'WS_CONNECTION_CLOSED';
export const WS_CONNECTION_END: 'WS_CONNECTION_END' = 'WS_CONNECTION_END';