export const FETCH_INGREDIENTS = "FETCH_INGREDIENTS";
export const FETCH_INGREDIENTS_STATE = "FETCH_INGREDIENTS_STATE";

export const GET_CONSTRUCTOR = "GET_CONSTRUCTOR";

export const ADD_INGREDIENT_DETAILS = "ADD_INGREDIENT_DETAILS";
export const DELETE_INGREDIENT_DETAILS = "DELETE_INGREDIENT_DETAILS";

export const FETCH_INGREDIENTS_ID = "FETCH_INGREDIENTS_ID";

export const ORDER_NUMBER = "ORDER_NUMBER";
export const ORDER_NUMBER_SUCCESS = "ORDER_NUMBER_SUCCESS";
export const ORDER_NUMBER_ERROR = "ORDER_NUMBER_ERROR";